### ISSUE TITLE
passwordless

### ISSUE THREAD

**Issue by carlhunterroach** [iuliiazhelem/Auth0CognitoIntegration#4]
I downloaded the project, configured it and compiled it and it ran fine.

I then tried to add `newEmailViewController` but Xcode couldn't resolve the method on `A0Lock`

```
A0Lock.sharedLock().newEmailViewController()
```

Xcode complains that A0Lock has no member 'newEmailViewController'
I've not modified the Podfile and so it contains `pod 'Lock'. '~> 1.24'`

Xcode can resolve `newSignUpViewController()` and `newLockViewController()`

How can I access `newEmailViewController`?

**Comment by iuliiazhelem** [comment]
You need to add the following to your `Podfile`:

```
pod 'Lock/Email'
```

For more details you can check also https://github.com/iuliiazhelem/Auth0PasswordlessConnection

**Comment by carlhunterroach** [comment]
thanks.
obviously makes sense
